### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [elkarouani/shodan-finder#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.4.3. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary shodanfinder -w /tmp/ext shodanfinder==1.4.3
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting shodanfinder==1.4.3
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/f30/f0c04d6cfe780/shodanfinder-1.4.3.tar.gz (3.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-vod9nqr8/shodanfinder/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-vod9nqr8/shodanfinder/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-vod9nqr8/shodanfinder/pip-egg-info
         cwd: /tmp/pip-wheel-vod9nqr8/shodanfinder/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-vod9nqr8/shodanfinder/setup.py", line 7, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by elkarouani** [comment]
Interesting issue, thank you for your contribution, ready to merge it
